### ISSUE TITLE
Извиняюсь, не так понял как и код, так и статью

### ISSUE THREAD

**Issue by glutesha** [lamer112311/DNNME#1]
Edit:Автор прав

**Comment by lamer112311** [comment]
> Привет, нашел твою статью по деанону человека при помощи твоей недопрограммы, и тут я решил чекнуть исходники и понял, что все ответы и "пробивы" бота заскриптованы. Хоть постыдился бы в открытый доступ лить такую шляпу.
> Если кому интересно, он будет постоянно выдавать это:
> Страна: Россия
> Регион: Екатеринбург
> Улица: 8 марта
> Google maps: https://clck.ru/RDFzp"""
> 
> Начинается эта канитель на 121 строке кода build

**Comment by lamer112311** [comment]
Ты не правильно понял смысл бота, важны не данные, которые выводятся по номеру, а данные, которые вводит жертва при "регистрации" а именно номер телефона и геолокацию. Заскриптованные данные нужны для того, чтобы скрыть подозрение у жертвы

**Comment by glutesha** [comment]
Извини, но я скорее понял неправильно статью, не репозиторий.  Но затейка прикольная
